### ISSUE TITLE
Not all choices showing up if there are more than 10 and order is wrong

### ISSUE THREAD

**Issue by iionly** [iionly/poll#21]
Problem is caused by not setting limit to false in getChoices() and not ordering by text instead of integer.

I'll make a PR (hopefully during the next few days).

**Comment by juho-jaakkola** [comment]
Why does the order affect the amount of items?

**Comment by iionly** [comment]
Display order metadata value of choices is

0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, etc.

The effect of the default limit of 10 is obvious: you only get 10 choices displayed even if a poll has more.

The effect of order_by if the values are interpreted as text (default) only shows up if there are at least 10 choices. In this case you don't get the choices in the expected order but instead it's

0, 10, 100, 110, 120, (...), 20, 200, etc.

But if order_by is used with "'as' => integer" then you get the expected order (as defined when adding/editing the poll).

**Comment by iionly** [comment]
Fixed in 1.X.3 releases of Poll plugin.
