### ISSUE TITLE
Possible feature: Multiple Choice

### ISSUE THREAD

**Issue by Pasley70** [iionly/poll#26]
For some small surveys it would be interesting to choose more than one option. Eg "On which days do you have time for a meeting"?.

**Comment by juho-jaakkola** [comment]
I was planning on implementing this a while ago, but I ran out of time. It would definitely be a useful feature!

**Comment by iionly** [comment]
Multiple choices is surely interesting (no time for implementing at the moment either). If you have a specific need for using polls to schedule meetings, you might want to check out the Event Poll plugin (https://elgg.org/plugins/2215337). In connection with the Event Calendar plugin it offers polls specifically for finding a time slot for meetings all participants can agree with.

**Comment by Pasley70** [comment]
@juho-jaakkola @iionly many thanx for your hints! Event Calendar plugin sounds interesting - i will have a look at it.

**Comment by Beaufort8** [comment]
I have got a litte suggestion for multiple choice: https://github.com/Beaufort8/poll
If you think this is a good way, i will work on that. The only thing i see at the moment are 
- multiple on-page-notifications
- differentiated presentation "voter" and "votes"

**Comment by iionly** [comment]
Feature added with https://github.com/iionly/poll/commit/6ba6385ba00a447c8de6c6bc1c294ce6b73fe58d.
