### ISSUE TITLE
Possible Feature: Notify creator on voting

### ISSUE THREAD

**Issue by Pasley70** [iionly/poll#28]
The creator might be informed about votings via notifications. Similar to comments or likes.

**Comment by juho-jaakkola** [comment]
I don't think it's a good idea to have this by default. On large sites it could mean hundreds of notifications.

Or at least Elgg core should first get support for content type specific notification settings: #7859

**Comment by Pasley70** [comment]
I am totally with you! That should be optional for the creator. In our case we have a very small network where every reaction is important.

**Comment by iionly** [comment]
Feature added by https://github.com/iionly/poll/commit/66323c438a14cd274830db0020cdb13040ac7216.

Notification of poll creator on voting can be enabled/disabled by plugin setting. The creator will receive / not receive notification depending on his/her site-wide, user-specific notification settings.
