### ISSUE TITLE
Annotation access level

### ISSUE THREAD

**Issue by Beaufort8** [iionly/poll#31]
Answers do not get the correct access level if you change the access level of the poll later (eg from private to public). If you change an answer AND the access level, the answers get the correct access level.

**Comment by iionly** [comment]
Thanks for reporting. I think I might have introduced this bug when I changed the handling of editing of polls with no longer deleting and re-creating the poll choices entitities in all cases but only when changed.

I'll try to fix that for the next release. As I see it, an update script will also become necessary to fix the access level set for choices for existing polls as it might have happened that the access level of some existing polls might already have been changed resulting in a mismatch of poll and choices for these entries.

**Comment by iionly** [comment]
Fixed by https://github.com/iionly/poll/commit/b725bac520a77a96232a8dc3d519d2299420a929.
