### ISSUE TITLE
Suggestion: Open/Close Polls

### ISSUE THREAD

**Issue by robleegutierrez** [iionly/poll#39]
Hi iionly,

I am a huge fan of your plugins. I am wondering if it is possible to add a open/close feature to the poll plugin? I think it will be beneficial and an important feature to let the poll owner open/close a poll after a current amount of hours of days of their liking. I think an automatic system will be extremely hard to code, but more of an edit options as of now to manually open and close voting. Thanks!

Best Regards,
Robert G.

**Comment by iionly** [comment]
I'm not sure I understand what you want to suggest. It is already possible to set an end date for polls. If you don't see it in the edit form you might need to enable it on the poll plugin settings page first.
